#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias e='emacs -nw'

# PS1='\u@\h \W > '
PS1='\[\e[1;94m\]\u\[\e[1;92m\]@\h:\W \[\e[1;94m\]> \[\e[m\]'

PATH=$PATH:/home/pierluigi/.scripts/
archey 
